### ISSUE TITLE
【vertx-core】groovy扩展新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#128]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-core/groovy/index.adoc#L157)

https://github.com/vertx-china/vertx-web-site/blob/6606d3cf55f8ea8615f5247be4c9afd2a5fffabe/docs/translation/vertx-core/groovy/index.adoc#L157-L161

**Comment by fofofofoxier** [comment]
领
