### ISSUE TITLE
【vertx-service-discovery】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#131]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-service-discovery/java/kubernetes-bridge.adoc#L32)

https://github.com/vertx-china/vertx-web-site/blob/6606d3cf55f8ea8615f5247be4c9afd2a5fffabe/docs/translation/vertx-service-discovery/java/kubernetes-bridge.adoc#L32

**Comment by fofofofoxier** [comment]
领

**Comment by fofofofoxier** [comment]
已更新
