### ISSUE TITLE
【vertx-cassandra-client】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#18]
需要翻译总文件数：3
需要翻译总行数：377
详情如下：
    docs\translation\vertx-cassandra-client\java\index.adoc行数：273
    docs\translation\vertx-cassandra-client\java\override\rxjava2.adoc行数：52
    docs\translation\vertx-cassandra-client\java\override.adoc行数：52

**Comment by fofofofoxier** [comment]
哦嚯
