### ISSUE TITLE
【vertx-web-openapi】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#180]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-web-openapi/java/index.adoc#L137)

https://github.com/vertx-china/vertx-web-site/blob/8b573c71f39b3c7aefcb01cd5f2bb1acc061dc24/docs/translation/vertx-web-openapi/java/index.adoc#L137-L300

翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-web-openapi/java/index.adoc#L304)

https://github.com/vertx-china/vertx-web-site/blob/8b573c71f39b3c7aefcb01cd5f2bb1acc061dc24/docs/translation/vertx-web-openapi/java/index.adoc#L304-L308

**Comment by dreamlike-ocean** [comment]
我认领了
