### ISSUE TITLE
【vertx-config】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#20]
需要翻译总文件数：10
需要翻译总行数：1346
详情如下：
    docs\translation\vertx-config\java\consul-store.adoc行数：61
    docs\translation\vertx-config\java\git-store.adoc行数：74
    docs\translation\vertx-config\java\hocon-format.adoc行数：54
    docs\translation\vertx-config\java\index.adoc行数：589
    docs\translation\vertx-config\java\kubernetes-store.adoc行数：81
    docs\translation\vertx-config\java\redis-store.adoc行数：60
    docs\translation\vertx-config\java\spring-store.adoc行数：58
    docs\translation\vertx-config\java\vault-store.adoc行数：255
    docs\translation\vertx-config\java\yaml-format.adoc行数：52
    docs\translation\vertx-config\java\zookeeper-store.adoc行数：62

**Comment by fofofofoxier** [comment]
领了
