### ISSUE TITLE
【vertx-sql-client】新增部分内容的翻译 

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#202]
> <h2>因为缓存原因，翻译index.adoc之外的其他文档，均不会编译。因此 `vertx-sql-client` 的子模块先翻译除 `index.adoc` 外的其他文件，再翻译 `index.adoc` </h2>

`vertx-sql-client` 新增文档 `pool_config.adoc` ，与之对应的四个子模块 `vertx-db2-client`, `vertx-mssql-client`, `vertx-mysql-client`, `vertx-pg-client` 均需要翻译此文档。可随便找一个模块翻译之后，复制到其他模块（注意代码部分可能有不同，提交时记得还原代码部分）。同时，还需要翻译各模块中 `index.adoc` 文件的标题（在文档最后，因前面所述原因，最后翻译这个标题）

同时还需要翻译以下片段：

翻译 `vertx-mssql-client` 以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mssql-client/java/index.adoc#L252)

https://github.com/vertx-china/vertx-web-site/blob/074f416ea28c2719e559aeb8843ed69c678282c5/docs/translation/vertx-mssql-client/java/index.adoc#L252-L254

翻译 `vertx-pg-client` 以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-pg-client/java/override/rxjava3.adoc#L4)

https://github.com/vertx-china/vertx-web-site/blob/074f416ea28c2719e559aeb8843ed69c678282c5/docs/translation/vertx-pg-client/java/override/rxjava3.adoc#L4-L20

**Comment by zhbotong** [comment]
认领
