### ISSUE TITLE
【vertx-mqtt】新增部分内容的翻译 

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#205]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mqtt/java/index.adoc#L522)

https://github.com/vertx-china/vertx-web-site/blob/074f416ea28c2719e559aeb8843ed69c678282c5/docs/translation/vertx-mqtt/java/index.adoc#L522-L569

**Comment by pigbayspy** [comment]
认领
