### ISSUE TITLE
【vertx-opentracing】新增部分内容的翻译 

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#206]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-opentracing/java/index.adoc#L100)

https://github.com/vertx-china/vertx-web-site/blob/074f416ea28c2719e559aeb8843ed69c678282c5/docs/translation/vertx-opentracing/java/index.adoc#L100-L249

**Comment by pigbayspy** [comment]
认领
