### ISSUE TITLE
【vertx-mssql-client】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#215]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mssql-client/java/index.adoc#L421)

https://github.com/vertx-china/vertx-web-site/blob/2d7a1d089fac1eb251d6068018d0a031988ee81e/docs/translation/vertx-mssql-client/java/index.adoc#L421-L471

**Comment by pigbayspy** [comment]
认领
