### ISSUE TITLE
【vertx-web-graphql】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#217]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-web-graphql/java/index.adoc#L298)

https://github.com/vertx-china/vertx-web-site/blob/2d7a1d089fac1eb251d6068018d0a031988ee81e/docs/translation/vertx-web-graphql/java/index.adoc#L298-L325

**Comment by pigbayspy** [comment]
认领
