### ISSUE TITLE
【vertx-core-polyglot】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#23]
需要翻译总文件数：2
需要翻译总行数：596
详情如下：
    docs\translation\vertx-core\groovy\index.adoc行数：430
    docs\translation\vertx-core\kotlin\index.adoc行数：166

**Comment by Leibnizhu** [comment]
与 #1 重复，关闭

**Comment by chengenzhao** [comment]
更新，换成kotlin和groovy的文档补充

**Comment by chengenzhao** [comment]
目前完成了kotlin的翻译，还需要groovy的翻译

**Comment by Hochikong** [comment]
想认领剩下的groovy部分
