### ISSUE TITLE
【vertx-mqtt】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#231]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mqtt/java/index.adoc#L34)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-mqtt/java/index.adoc#L34
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mqtt/java/index.adoc#L51)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-mqtt/java/index.adoc#L51
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mqtt/java/index.adoc#L107)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-mqtt/java/index.adoc#L107-L108
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mqtt/java/index.adoc#L192)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-mqtt/java/index.adoc#L192-L193
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mqtt/java/index.adoc#L195)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-mqtt/java/index.adoc#L195-L196
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mqtt/java/index.adoc#L218)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-mqtt/java/index.adoc#L218-L219
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mqtt/java/index.adoc#L239)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-mqtt/java/index.adoc#L239
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mqtt/java/index.adoc#L241)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-mqtt/java/index.adoc#L241
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mqtt/java/index.adoc#L252)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-mqtt/java/index.adoc#L252-L253
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mqtt/java/index.adoc#L281)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-mqtt/java/index.adoc#L281-L283

**Comment by pigbayspy** [comment]
认领
