### ISSUE TITLE
【vertx-opentelemetry】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#232]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-opentelemetry/java/index.adoc#L26)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-opentelemetry/java/index.adoc#L26-L27

**Comment by pigbayspy** [comment]
认领
