### ISSUE TITLE
【vertx-redis-client】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#234]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-redis-client/java/index.adoc#L58)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-redis-client/java/index.adoc#L58
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-redis-client/java/index.adoc#L199)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-redis-client/java/index.adoc#L199-L224

**Comment by pigbayspy** [comment]
认领
