### ISSUE TITLE
【vertx-web-graphql】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#238]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-web-graphql/java/index.adoc#L109)

https://github.com/vertx-china/vertx-web-site/blob/df1c70a930303105ab89e6069ae1eb8fb8fe4d3e/docs/translation/vertx-web-graphql/java/index.adoc#L109-L147

**Comment by pigbayspy** [comment]
认领
