### ISSUE TITLE
【vertx-oracle-client】oracle新增部分内容的翻译及vertx-sql-client新增通用文件翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#257]
vertx-sql-client子项目通用的文件 `pool__sharing.adoc` 翻译，并翻译各子项目 `index.adoc` 中对应位置的标题。（点击下面子项目可在线翻译）

- [ ] [vertx-db2-client](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-db2-client/java/index.adoc#L211)
- [ ] [vertx-mssql-client](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mssql-client/java/index.adoc#L481)
- [ ] [vertx-mysql-client](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mysql-client/java/index.adoc#L183)
- [ ] [vertx-oracle-client](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-oracle-client/java/index.adoc#L172)
- [ ] [vertx-pg-client](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-pg-client/java/index.adoc#L202)

> 注意：pool_sharing.adoc 文件只需要翻译一个文件，然后复制到所有子项目

【vertx-db2-client】新增部分内容的翻译

https://github.com/vertx-china/vertx-web-site/blob/ea567132b15b1a84f0cee157f0385d82504b5007/docs/translation/vertx-db2-client/java/index.adoc#L211
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-db2-client/java/pool_sharing.adoc#L1)

https://github.com/vertx-china/vertx-web-site/blob/ea567132b15b1a84f0cee157f0385d82504b5007/docs/translation/vertx-db2-client/java/pool_sharing.adoc#L1-L49

【vertx-mssql-client】新增部分内容的翻译

https://github.com/vertx-china/vertx-web-site/blob/ea567132b15b1a84f0cee157f0385d82504b5007/docs/translation/vertx-mssql-client/java/index.adoc#L481
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mssql-client/java/pool_sharing.adoc#L1)

https://github.com/vertx-china/vertx-web-site/blob/ea567132b15b1a84f0cee157f0385d82504b5007/docs/translation/vertx-mssql-client/java/pool_sharing.adoc#L1-L49

【vertx-mysql-client】新增部分内容的翻译

https://github.com/vertx-china/vertx-web-site/blob/ea567132b15b1a84f0cee157f0385d82504b5007/docs/translation/vertx-mysql-client/java/index.adoc#L183
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-mysql-client/java/pool_sharing.adoc#L1)

https://github.com/vertx-china/vertx-web-site/blob/ea567132b15b1a84f0cee157f0385d82504b5007/docs/translation/vertx-mysql-client/java/pool_sharing.adoc#L1-L49

【vertx-oracle-client】新增部分内容的翻译

https://github.com/vertx-china/vertx-web-site/blob/ea567132b15b1a84f0cee157f0385d82504b5007/docs/translation/vertx-oracle-client/java/index.adoc#L172
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-oracle-client/java/index.adoc#L205)

https://github.com/vertx-china/vertx-web-site/blob/ea567132b15b1a84f0cee157f0385d82504b5007/docs/translation/vertx-oracle-client/java/index.adoc#L205-L219
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-oracle-client/java/index.adoc#L235)

https://github.com/vertx-china/vertx-web-site/blob/ea567132b15b1a84f0cee157f0385d82504b5007/docs/translation/vertx-oracle-client/java/index.adoc#L235-L281

【vertx-pg-client】新增部分内容的翻译

https://github.com/vertx-china/vertx-web-site/blob/ea567132b15b1a84f0cee157f0385d82504b5007/docs/translation/vertx-pg-client/java/index.adoc#L206
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-pg-client/java/pool_sharing.adoc#L1)

https://github.com/vertx-china/vertx-web-site/blob/ea567132b15b1a84f0cee157f0385d82504b5007/docs/translation/vertx-pg-client/java/pool_sharing.adoc#L1-L49

**Comment by pigbayspy** [comment]
认领

**Comment by pigbayspy** [comment]
vertx-oracle-client 下没有看到 pool_sharing.adoc 文件，是不是我要手动加一下

**Comment by okou19900722** [comment]
没有就先不管，估计是oracle模块没有处理这个文件，或者这个文件处理出错了，所以没有这个文件
