### ISSUE TITLE
【vertx-kafka-client】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#268]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-kafka-client/java/index.adoc#L79)

https://github.com/vertx-china/vertx-web-site/blob/7747173822dd52ccecf7c21aafc4ddfb45ba3d4e/docs/translation/vertx-kafka-client/java/index.adoc#L79
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-kafka-client/java/index.adoc#L908)

https://github.com/vertx-china/vertx-web-site/blob/7747173822dd52ccecf7c21aafc4ddfb45ba3d4e/docs/translation/vertx-kafka-client/java/index.adoc#L908

**Comment by darkokoa** [comment]
认领
