### ISSUE TITLE
【vertx-circuit-breaker】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#277]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-circuit-breaker/java/index.adoc#L252)

https://github.com/vertx-china/vertx-china.github.io/blob/3088af695bed8d2d426f0da88752b80e306c0caa/docs/translation/vertx-circuit-breaker/java/index.adoc#L252-L262

**Comment by imtzc** [comment]
您好，邮件已经收到，我会尽快给您回复。

**Comment by chengenzhao** [comment]
这段翻译好了
