### ISSUE TITLE
【vertx-grpc-netty】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#280]
需要翻译总文件数：1
需要翻译总行数：595
详情如下：
docs\translation\vertx-grpc-netty\java\index.adoc行数：595

**Comment by krevig** [comment]
认领

**Comment by chengenzhao** [comment]
> 认领

你好，fork到本地仓库，然后就可以用idea等ide读取你本地的仓库，进行编辑了
编辑完成后提交pr给vertx-china的仓库就行
