### ISSUE TITLE
【vertx-unit】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#284]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-unit/java/index.adoc#L1005)

https://github.com/vertx-china/vertx-china.github.io/blob/3088af695bed8d2d426f0da88752b80e306c0caa/docs/translation/vertx-unit/java/index.adoc#L1005-L1009

**Comment by portgas-an** [comment]
认领
