### ISSUE TITLE
【vertx-circuit-breaker】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#303]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-circuit-breaker/java/index.adoc#L261)

https://github.com/vertx-china/vertx-china.github.io/blob/bc2f3c63009f634161fa50b5864e4e709e531e72/docs/translation/vertx-circuit-breaker/java/index.adoc#L261-L279

翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-circuit-breaker/java/index.adoc#L293)

https://github.com/vertx-china/vertx-china.github.io/blob/bc2f3c63009f634161fa50b5864e4e709e531e72/docs/translation/vertx-circuit-breaker/java/index.adoc#L293

**Comment by pigbayspy** [comment]
认领
