### ISSUE TITLE
【vertx-micrometer-metrics】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#315]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-micrometer-metrics/java/index.adoc#L78)

https://github.com/vertx-china/vertx-china.github.io/blob/49e68730e9b39b9ecfd593eda563de17064c6d9d/docs/translation/vertx-micrometer-metrics/java/index.adoc#L78-L130

**Comment by pigbayspy** [comment]
认领
