### ISSUE TITLE
【vertx-web-validation】新增部分内容的翻译

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#318]
翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-web-validation/java/index.adoc#L103)

https://github.com/vertx-china/vertx-china.github.io/blob/49e68730e9b39b9ecfd593eda563de17064c6d9d/docs/translation/vertx-web-validation/java/index.adoc#L103-L105

**Comment by pigbayspy** [comment]
认领
