### ISSUE TITLE
【vertx-mail-client】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#38]
需要翻译总文件数：1
需要翻译总行数：272
详情如下：
    docs\translation\vertx-mail-client\java\index.adoc行数：272

**Comment by mm0rz** [comment]
认领

**Comment by okou19900722** [comment]
@mm0rz 这个的翻译有没有开始，是继续翻译还是准备放弃了？

**Comment by PassXml** [comment]
没人来的话...我认领了
