### ISSUE TITLE
【vertx-mongo-client】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#41]
需要翻译总文件数：3
需要翻译总行数：1199
详情如下：
    docs\translation\vertx-mongo-client\java\index.adoc行数：1129
    docs\translation\vertx-mongo-client\java\override\rxjava2.adoc行数：35
    docs\translation\vertx-mongo-client\java\override.adoc行数：35

**Comment by hydrawalker** [comment]
vertx 中国你好，我想翻译vertx-mongo-client 的文档
