### ISSUE TITLE
【vertx-mysql-client】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#43]
需要翻译总文件数：6
需要翻译总行数：1518
详情如下：
    docs\translation\vertx-mysql-client\java\connections.adoc行数：77
    docs\translation\vertx-mysql-client\java\cursor.adoc行数：73
    docs\translation\vertx-mysql-client\java\index.adoc行数：1078
    docs\translation\vertx-mysql-client\java\queries.adoc行数：163
    docs\translation\vertx-mysql-client\java\tracing.adoc行数：21
    docs\translation\vertx-mysql-client\java\transactions.adoc行数：106

**Comment by sfiloveyou** [comment]
我认领
