### ISSUE TITLE
【vertx-pg-client】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#45]
需要翻译总文件数：9
需要翻译总行数：1608
详情如下：
    docs\translation\vertx-pg-client\java\connections.adoc行数：77
    docs\translation\vertx-pg-client\java\cursor.adoc行数：88
    docs\translation\vertx-pg-client\java\index.adoc行数：916
    docs\translation\vertx-pg-client\java\override\kotlin.adoc行数：2
    docs\translation\vertx-pg-client\java\override\rxjava2.adoc行数：116
    docs\translation\vertx-pg-client\java\override.adoc行数：118
    docs\translation\vertx-pg-client\java\queries.adoc行数：163
    docs\translation\vertx-pg-client\java\tracing.adoc行数：21
    docs\translation\vertx-pg-client\java\transactions.adoc行数：107

**Comment by CatCodeMe** [comment]
我来接锅

**Comment by CatCodeMe** [comment]
docs\translation\vertx-pg-client\java\connections.adoc行数：77
docs\translation\vertx-pg-client\java\cursor.adoc行数：88
docs\translation\vertx-pg-client\java\index.adoc行数：916
docs\translation\vertx-pg-client\java\override\kotlin.adoc行数：2
docs\translation\vertx-pg-client\java\override\rxjava2.adoc行数：116
docs\translation\vertx-pg-client\java\override.adoc行数：118
docs\translation\vertx-pg-client\java\queries.adoc行数：163
docs\translation\vertx-pg-client\java\tracing.adoc行数：21
docs\translation\vertx-pg-client\java\transactions.adoc行数：107
