### ISSUE TITLE
【vertx-rx】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#49]
需要翻译总文件数：2
需要翻译总行数：1397
详情如下：
    docs\translation\vertx-rx\java\index.adoc行数：733
    docs\translation\vertx-rx\java2\index.adoc行数：664

**Comment by chengenzhao** [comment]
rx1低优先级了
翻译完rx2就是成功

**Comment by wang007** [comment]
翻译完成 rx2 就算成功

**Comment by chengenzhao** [comment]
https://github.com/VertxChina/vertx-translation-chinese/blob/dev/reactive/Rx.md

之前的rx的翻译
