### ISSUE TITLE
【vertx-service-discovery】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#50]
需要翻译总文件数：5
需要翻译总行数：1278
详情如下：
    docs\translation\vertx-service-discovery\java\consul-bridge.adoc行数：54
    docs\translation\vertx-service-discovery\java\docker-links-bridge.adoc行数：41
    docs\translation\vertx-service-discovery\java\index.adoc行数：1057
    docs\translation\vertx-service-discovery\java\kubernetes-bridge.adoc行数：67
    docs\translation\vertx-service-discovery\java\redis-backend.adoc行数：59

**Comment by fofofofoxier** [comment]
我领
docs\translation\vertx-service-discovery\java\consul-bridge.adoc行数：54
docs\translation\vertx-service-discovery\java\docker-links-bridge.adoc行数：41
docs\translation\vertx-service-discovery\java\index.adoc行数：1057
docs\translation\vertx-service-discovery\java\kubernetes-bridge.adoc行数：67
docs\translation\vertx-service-discovery\java\redis-backend.adoc行数：5
