### ISSUE TITLE
【vertx-service-factory】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#51]
需要翻译总文件数：1
需要翻译总行数：129
详情如下：
    docs\translation\vertx-service-factory\java\index.adoc行数：129

**Comment by superxwx** [comment]
这部分我去做：

需要翻译总文件数：1
需要翻译总行数：129
详情如下：
docs\translation\vertx-service-factory\java\index.adoc行数：129
