### ISSUE TITLE
【vertx-web】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#62]
需要翻译总文件数：1
需要翻译总行数：3982
详情如下：
    docs\translation\vertx-web\java\index.adoc行数：3982

**Comment by okou19900722** [comment]
[`处理 SockJS 套接字`](https://github.com/vertx-china/vertx-web-site/blob/master/docs/translation/vertx-web/java/index.adoc#_handling_sockjs_sockets) 这一段后面加了几句话需要翻译一下。

**Comment by okou19900722** [comment]
4.0.3版本新增下面两段在已翻译段落中，需要翻译一下

翻译以下片段，[点击在线翻译](https://github.com/vertx-china/vertx-web-site/edit/master/docs/translation/vertx-web/java/index.adoc#L422)

https://github.com/vertx-china/vertx-web-site/blob/6606d3cf55f8ea8615f5247be4c9afd2a5fffabe/docs/translation/vertx-web/java/index.adoc#L422-L423

https://github.com/vertx-china/vertx-web-site/blob/6606d3cf55f8ea8615f5247be4c9afd2a5fffabe/docs/translation/vertx-web/java/index.adoc#L431

好了解决了

**Comment by dreamlike-ocean** [comment]
我想认领一下，我从route order开始翻译
