### ISSUE TITLE
【vertx-web-api-contract】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#63]
需要翻译总文件数：3
需要翻译总行数：422
详情如下：
    docs\translation\vertx-web-api-contract\java\index.adoc行数：348
    docs\translation\vertx-web-api-contract\java\override\rxjava2.adoc行数：37
    docs\translation\vertx-web-api-contract\java\override.adoc行数：37

**Comment by fofofofoxier** [comment]
认领

**Comment by chengenzhao** [comment]
该子项已经deprecated了，我直接merge了，无需花太多时间在这上面
