### ISSUE TITLE
【vertx-web-client】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#65]
需要翻译总文件数：3
需要翻译总行数：1045
详情如下：
    docs\translation\vertx-web-client\java\index.adoc行数：913
    docs\translation\vertx-web-client\java\override\rxjava2.adoc行数：66
    docs\translation\vertx-web-client\java\override.adoc行数：66

**Comment by sfiloveyou** [comment]
我认领
