### ISSUE TITLE
【vertx-web-graphql】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#66]
需要翻译总文件数：3
需要翻译总行数：430
详情如下：
    docs\translation\vertx-web-graphql\java\index.adoc行数：348
    docs\translation\vertx-web-graphql\java\override\rxjava2.adoc行数：41
    docs\translation\vertx-web-graphql\java\override.adoc行数：41

**Comment by chengenzhao** [comment]
这个其实我都翻译一半了
