### ISSUE TITLE
【vertx-zipkin】的翻译和校对

### ISSUE THREAD

**Issue by okou19900722** [vertx-china/vertx-china.github.io#69]
需要翻译总文件数：1
需要翻译总行数：95
详情如下：
    docs\translation\vertx-zipkin\java\index.adoc行数：95

**Comment by superxwx** [comment]
这部分我去做：

需要翻译总文件数：1
需要翻译总行数：95
详情如下：
docs\translation\vertx-zipkin\java\index.adoc行数：95
